export const FRESHMAN_LOGIN_FEATURE_FLAG_KEY = "FRESHMAN_LOGIN";
export const FRESHMAN_MIGRATION_FEATURE_FLAG_KEY = "FRESHMAN_MIGRATION";
export const FRESHMAN_SIGNUP_FEATURE_FLAG_KEY = "FRESHMAN_SIGNUP";
